[project]
name = "fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiomysql>=0.3.2",
    "fastapi[standard]>=0.128.4",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.46",
]
